#!/usr/bin/env python3
"""
bin2inc.py - convert a binary file to an Intel-8080 assembler INCLUDE file.

Common converter for FDIPL80, HDIPL80 and MASTERIPL80.

Examples:
    python3 bin2inc.py FDIPL80.BIN FDIPL80.INC --label FDIPL80
    python3 bin2inc.py HDIPL80.BIN HDIPL80.INC --label HDIPL80
    python3 bin2inc.py MASTERIPL80.BIN MASTERIPL80.INC --label MASTERIPL80
"""

import argparse
import sys
from pathlib import Path


def hex8080(value: int) -> str:
    """Return an unambiguous Intel-8080 hexadecimal literal."""
    s = f"{value:02X}"
    if s[0] in "ABCDEF":
        s = "0" + s
    return s + "H"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert BIN to Intel-8080 DB include file."
    )
    parser.add_argument("input", type=Path, help="input binary file")
    parser.add_argument("output", type=Path, help="output .INC file")
    parser.add_argument("--label", default="FDIPL80",
                        help="assembler label (default: FDIPL80)")
    parser.add_argument("--bytes-per-line", type=int, default=16,
                        help="bytes per DB line (default: 16)")
    parser.add_argument("--size", type=int, default=512,
                        help="required binary size (default: 512)")
    parser.add_argument("--no-size-check", action="store_true",
                        help="do not require an exact binary size")
    args = parser.parse_args()

    if args.bytes_per_line < 1:
        parser.error("--bytes-per-line must be >= 1")
    if args.size < 1:
        parser.error("--size must be >= 1")

    try:
        data = args.input.read_bytes()
    except OSError as exc:
        print(f"bin2inc: cannot read {args.input}: {exc}", file=sys.stderr)
        return 1

    if not data:
        print("bin2inc: input file is empty", file=sys.stderr)
        return 1

    if not args.no_size_check and len(data) != args.size:
        print(
            f"bin2inc: ERROR: {args.input} is {len(data)} bytes; "
            f"expected exactly {args.size} bytes",
            file=sys.stderr,
        )
        return 2

    if len(data) == 512 and data[-2:] != b"\x55\xaa":
        print(
            "bin2inc: WARNING: 512-byte image does not end in 55 AA",
            file=sys.stderr,
        )

    lines = [
        "; Generated by bin2inc.py. Do not edit by hand.",
        f"; Source: {args.input.name}",
        f"; Size: {len(data)} bytes",
        "",
        f"{args.label}:",
    ]

    for offset in range(0, len(data), args.bytes_per_line):
        chunk = data[offset:offset + args.bytes_per_line]
        values = ",".join(hex8080(b) for b in chunk)
        lines.append(f"        DB      {values}")

    lines += [
        f"{args.label}_END:",
        f"{args.label}_SIZE EQU {args.label}_END-{args.label}",
        "",
    ]

    output_bytes = "\r\n".join(lines).encode("ascii")

    try:
        args.output.write_bytes(output_bytes)
    except OSError as exc:
        print(f"bin2inc: cannot write {args.output}: {exc}", file=sys.stderr)
        return 1

    print(
        f"{args.input}: {len(data)} bytes -> "
        f"{args.output} ({args.label}, {args.bytes_per_line} bytes/line)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
